Repository Nitro4Friends/Nitro4Friends-Backend, pull requests merged in 2023-10, with the labels that each got.

#5 Added basic oauth2.0 🧪
  .env.example
  build.gradle.kts
  src/main/kotlin/com/nitro4friends/Nitro4Friends.kt
  src/main/kotlin/com/nitro4friends/Start.kt
  src/main/kotlin/com/nitro4friends/api/RestAPI.kt
  src/main/kotlin/com/nitro4friends/api/handlers/DiscordRedirect.kt
  src/main/kotlin/com/nitro4friends/model/discord/AccessPacket.kt
  src/main/kotlin/com/nitro4friends/utils/DiscordEndpoints.kt
  src/main/kotlin/com/nitro4friends/utils/Environment.kt
Labels: enhancement

#7 SQL Objects and Models 🧩
  build.gradle.kts
  src/main/kotlin/com/nitro4friends/Nitro4Friends.kt
  src/main/kotlin/com/nitro4friends/api/handlers/DiscordRedirect.kt
  src/main/kotlin/com/nitro4friends/model/CreditsModel.kt
  src/main/kotlin/com/nitro4friends/model/InvitesModel.kt
  src/main/kotlin/com/nitro4friends/model/RedeemModel.kt
  src/main/kotlin/com/nitro4friends/model/UserModel.kt
  src/main/kotlin/com/nitro4friends/model/discord/DiscordUser.kt
  src/main/kotlin/com/nitro4friends/utils/DatabaseConnection.kt
  src/main/kotlin/com/nitro4friends/utils/DiscordEndpoints.kt
Labels: enhancement

#9 Now it's right 🎂
  src/main/kotlin/com/nitro4friends/api/handlers/DiscordRedirect.kt
  src/main/kotlin/com/nitro4friends/model/CreditsModel.kt
  src/main/kotlin/com/nitro4friends/model/InvitesModel.kt
  src/main/kotlin/com/nitro4friends/model/RedeemModel.kt
  src/main/kotlin/com/nitro4friends/model/UserModel.kt
Labels: bug, chore

#11 Public data endpoint
  src/main/kotlin/com/nitro4friends/api/RestAPI.kt
  src/main/kotlin/com/nitro4friends/api/handlers/DataEndpoints.kt
  src/main/kotlin/com/nitro4friends/api/handlers/DiscordRedirect.kt
  src/main/kotlin/com/nitro4friends/cache/UserStorage.kt
  src/main/kotlin/com/nitro4friends/model/ClientPublicDataModel.kt
  src/main/kotlin/com/nitro4friends/model/CreditsModel.kt
  src/main/kotlin/com/nitro4friends/model/InvitesModel.kt
  src/main/kotlin/com/nitro4friends/model/RedeemModel.kt
Labels: enhancement

#12 Created manifest ⚙️
  build.gradle.kts
Labels: bug

#13 Added Cors
  src/main/kotlin/com/nitro4friends/api/RestAPI.kt
  src/main/kotlin/com/nitro4friends/api/handlers/DataEndpoints.kt
Labels: bug

#15 Fixed license and issues links
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
